### PR TITLE
fix tests

### PR DESCRIPTION
**Pull request by SamVerschueren**
Had to rewrite some tests because of https://github.com/sindresorhus/ava/pull/360. Not sure if it can be written cleaner or better?

### CODE REVIEW

**Comment by jamestalmage** [comment]
@SamVerschueren - I think https://github.com/sindresorhus/ava/pull/395 would solve this better. Thoughts?

**Comment by SamVerschueren** [comment]
That's how I did it before https://github.com/sindresorhus/ava/pull/360. So not sure why it was removed...

**Comment by jamestalmage** [comment]
It was removed in `360`. You no longer **need** to await a `t.throws` or `t.doesNotThrow`, but I think it was an oversight that you no longer may do so.

**Comment by SamVerschueren** [comment]
> You no longer need to await a t.throws or t.doesNotThrow

Which is nice :)

> I think it was an oversight that you no longer may do so.

You can't always oversee all the use cases :).

**Comment by sindresorhus** [comment]
@SamVerschueren Why not just remove the `await`? Throws supports waiting for the promise.

**Comment by SamVerschueren** [comment]
Because it needs to know the time it takes to reject the promise, I have to wait for the promise to reject.

**Comment by sindresorhus** [comment]
Ah, missed that.

**Pull request merged**
